# --- Configuración Requerida ---
sonar.projectKey=camilo_citasalud-fs-backend
sonar.organization=camilo
sonar.host.url=https://sonarcloud.io

# --- Propiedades del Código Fuente ---
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# --- ¡ESTA ES LA LÍNEA MÁS IMPORTANTE! ---
# Le dice a SonarCloud dónde está el reporte de cobertura de JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml